version: '3.7'
name: hackathon

services:
  app:
    restart: always
    build:
      dockerfile: app.dockerfile
    volumes:
      - ./:/src
      - static:/src/static:mode=777
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      my-ms:

  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      my-ms:

volumes:
  pg_data:
  static:

networks:
  my-ms:
    driver: bridge
