version: '3.7'

services:
  app:
    restart: always
    build:
      dockerfile: fastapi.dockerfile
    volumes:
      - ./:/src
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  worker:
    build:
      dockerfile: ./celery.dockerfile
    command: celery -A src.celery:app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - db

volumes:
  pg_data: